version: '3.8'
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: java-api
    restart: always
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    restart: always
    volumes:
      - ./db/:/data/db